### PR TITLE
Create pull request template

### PR DESCRIPTION
**Pull request by leahriffell**
Hey team! I followed the instructions from this [link](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) on creating a PR template. Once this is merged, it should automatically populate this content in any new PR we create.

### CODE REVIEW

**Comment by LHJE** [comment]
Looks good to me!

**Review by LHJE — APPROVED** [review]
Such a cool little hack!

**Comment by priyapower** [comment]
AMAZING! Thanks for finding this and sharing out!

**Review by priyapower — COMMENTED** [review]
AMAZING! Thanks for finding this and sharing out!

**Pull request merged**
